# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the vLLM project
import asyncio
from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Callable


@dataclass
class InputInfo:
    batch_size: int
    num_tokens: list[int]
    total_num_tokens: int


@dataclass
class SplitConfig:
    """Configuration for nano-batch splitting."""

    num_nano_batches: int
    batch_sizes: list[int]
    batch_indices: list[int]
    num_tokens: list[int]
    split_indices: list[int]


@dataclass(eq=False, frozen=True)
class OperatorHandle:
    module_name: str
    nano_batch_idx: int
    debug_info: dict[str, str]


class ExecutionContext:
    """Context passed to the scheduler"""

    def __init__(
        self,
        split_config: SplitConfig,
        op_queue: dict[int, asyncio.Queue[OperatorHandle]],
        execute_queue: asyncio.Queue[
            tuple[
                OperatorHandle | tuple[OperatorHandle],
                Callable | None,
                asyncio.Event,
            ]
        ],
    ) -> None:
        """Initialize the execution context.

        Args:
            split_config: The split configuration generated by the scheduler.
            op_queue: The queue to receive the ready operators from the engine.
            execute_queue: The queue to send execution requests to the engine.
        """
        self._split_config = split_config
        self._op_queue = op_queue
        self._execute_queue = execute_queue

    @property
    def split_config(self) -> SplitConfig:
        return self._split_config

    async def pop(self, nano_batch_idx: int) -> OperatorHandle:
        return await self._op_queue[nano_batch_idx].get()

    async def execute(
        self,
        operator: OperatorHandle | tuple[OperatorHandle],
        func: Callable | None = None,
    ) -> None:
        done_event = asyncio.Event()
        await self._execute_queue.put((operator, func, done_event))
        await done_event.wait()


class OpSchedulerBase(ABC):
    def __init__(self, policy_name: str):
        self.policy_name = policy_name

    @abstractmethod
    def get_split_config(self, input_info: InputInfo) -> SplitConfig:
        pass

    @abstractmethod
    async def schedule(self, context: ExecutionContext) -> None:
        pass
